language: ruby
cache: bundler

rvm:
  - 2.6
  - 2.4

notifications:
    email: false

before_install: gem update --system
install: bash scripts/bootstrap.sh
script: bash scripts/cibuild.sh

env:
  matrix:
    - JEKYLL_VERSION="~> 3.5.0"
    - JEKYLL_VERSION="~> 3.8.0"
    - JEKYLL_VERSION="~> 4.0.0"