title: ./gauthamchettiar # The title of the blog
author: Gautham Chettiar # Your name 
email: gauthamchettiar@gmail.com # your email shown in the footer
url: "https://gauthamchettiar.com" # this is your site's root address.
description: > # this means to ignore newlines until "show_excerpts:"
  Just some place to share a piece of my thought. I am trying to maintain it as a part technical, part personal blog. I will appreciate your feedback, my details at the bottom of this page.
favicon: "./favicon.ico" # set the favicon of the site 

show_excerpts: true # set to true to show excerpts on the homepage
google_analytics: UA-30365710-2
# Moving date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
moving:
  avatar_url: "https://scontent-bom1-1.cdninstagram.com/v/t51.2885-19/s150x150/107041366_646361939565738_7988283480820379826_n.jpg?_nc_ht=scontent-bom1-1.cdninstagram.com&_nc_ohc=-ERq8PCXYQsAX9gm-hx&oh=36abfa8b523ee5b1735a63ef2a9d0d2a&oe=5F3525EC" # avatar in about page
  about_you: When things don't make sense, let go of it! # short description about you in about page
  date_format: "%b %d" # date format of posts in home page
  back_to: "Home" # In the post page, you have a back button above the title, you can custom the text by yourself.

  # generate social links in about page.
  social_links:
    # twitter: 
    github:  gauthamchettiar
    # rss: RSS
    # dribbble: 
    # facebook: ""
    # flickr:   
    instagram: gautham_chettiar
    linkedin: gauthamchettiar
    # pinterest: 
    # youtube: 
    # youtube_channel: 
    # youtube_channel_name: 
    # telegram: 
    # googleplus: 
    # microdotblog: 
    # reddit: 

    # Mastodon instances
    # mastodon:
    # - username: 
    #   instance: 
    # - username: 
    #   instance: 

# Build settings
theme: moving # note, please use huangyz0918/moving if you want to publish to Github Pages.
# remote_theme: huangyz0918/moving

plugins:
  - jekyll-feed
  - jekyll-seo-tag
