title: ./gauthamchettiar # The title of the blog
author: Gautham Chettiar # Your name 
email: gauthamchettiar@gmail.com # your email shown in the footer
url: "" # this is your site's root address.
description: > # this means to ignore newlines until "show_excerpts:"
  Just some place to share a piece of my thought. I am trying to maintain it as a part technical, part personal blog. And yes, Have a good day! 
favicon: "./favicon.ico" # set the favicon of the site 

show_excerpts: true # set to true to show excerpts on the homepage
  
# Moving date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
moving:
  avatar_url: "https://scontent-bom1-1.cdninstagram.com/v/t51.2885-19/s320x320/44299002_247919542571832_4074307973868945408_n.jpg?_nc_ht=scontent-bom1-1.cdninstagram.com&_nc_ohc=fWG8FMmz-sYAX-If4Rs&oh=c373e778e1707aa587bc2b4d06780afa&oe=5F308002" # avatar in about page
  about_you: When things don't make sense, let go of it! # short description about you in about page
  date_format: "%b %d" # date format of posts in home page
  back_to: "Home" # In the post page, you have a back button above the title, you can custom the text by yourself.

  # generate social links in about page.
  social_links:
    # twitter: 
    github:  gauthamchettiar
    # rss: RSS
    # dribbble: 
    # facebook: ""
    # flickr:   
    instagram: gautham_chettiar
    linkedin: gauthamchettiar
    # pinterest: 
    # youtube: 
    # youtube_channel: 
    # youtube_channel_name: 
    # telegram: 
    # googleplus: 
    # microdotblog: 
    # reddit: 

    # Mastodon instances
    # mastodon:
    # - username: 
    #   instance: 
    # - username: 
    #   instance: 

# Build settings
theme: moving # note, please use huangyz0918/moving if you want to publish to Github Pages.
# remote_theme: huangyz0918/moving

plugins:
  - jekyll-feed
  - jekyll-seo-tag
