#Google Analytics
analytics-id: #leave blank to not use Analytics

#Subtitle
subtitle:
  active: false
  text: A Personal Blog, To Scribble My Thoughts!

#Nav 
nav:
  pages:
    active: false
  social:
    active: true

#Featured images in homepage
featured-img:
  active: false

#Show categories at the end of posts
categories:
  active: true

#Show date and read time under the post title
date-under-post:
  active: true

#Use MathJAX
mathjax:
  active: false

#Show related posts based on categories
related-posts:
  active: false
  title: "Similar Posts"

#Comments
comments: true