defaults: &defaults
  working_directory: ~/repo
version: 2
jobs:
  build:
    <<: *defaults
    docker:
      - image: starefossen/ruby-node
    environment:
      BUNDLE_PATH: ~/repo/vendor/bundle
    steps:
      - checkout
      - run:
          name: Run Setup
          command:  |
            gem install bundler --conservative
            bundle check || bundle install
            bundle update
            npm install -g yarn
            yarn install --modules-folder ./_assets/yarn
            bundle exec jekyll build
      - run:
          name: HTMLProofer tests
          command: |
            bundle exec htmlproofer _site \
              --only-4xx \
              --allow-hash-href \
              --assume-extension \
              --check-opengraph \
              --url-ignore "feed.xml"
      - run:
          name: Deploy to gh-pages Branch
          command: |
            echo "COPY REQUIRED FILES TO '../_site' FOLDER"
            mkdir ../_site
            cp -r _site/* .git .gitignore ../_site
            rm -rf _site/ _assets/yarn/
            mkdir ../_site/.circleci
            cp dummy.yml ../_site/.circleci/config.yml
            pwd
            ls -la

            echo "SETTING UP GITHUB CREDENTIALS"
            git config credential.helper 'cache --timeout=120'
            git config user.email "${GITHUB_EMAIL}"
            git config user.name "${GITHUB_USERNAME}"
            git remote set-url origin https://${GITHUB_TOKEN}@github.com/gauthamchettiar/gauthamchettiar.github.io.git
            
            echo "CHECKOUT 'gh-pages' BRANCH"
            git checkout gh-pages
            
            echo "UPDATE 'gh-pages' BRANCH WITH SITE_DATA"
            rm -rf *
            mv ../_site/* .
            pwd
            ls -la

            echo "COMMIT AND PUSH TO BRANCH 'gh-pages'"
            git add -fA
            git commit --allow-empty -m "Page release ${CIRCLE_BUILD_NUM} from ${CIRCLE_BRANCH}"
            git push -f -q origin gh-pages
            git tag -a "release_${CIRCLE_BRANCH}_${CIRCLE_BUILD_NUM}" -m "Release based on build ${CIRCLE_BUILD_NUM}"
            git push -q --tags https://${GITHUB_TOKEN}@github.com/gauthamchettiar/gauthamchettiar.github.io.git
      
      # - persist_to_workspace:
      #     root: ./
      #     paths:
      #       - _site
  # deploy:
  #   machine: true
  #   working_directory: ~/repo
  #   steps:
  #     - run:
  #         name: Deploy build to GitHub Pages
  #         command: |
  #           ls -l
  #           ./bin/deploy
workflows:
  version: 2
  build-and-deploy:
    jobs:
      build:
        filters:
          branches:
            only: master