defaults: &defaults
  working_directory: ~/repo
version: 2
jobs:
  build:
    <<: *defaults
    docker:
      - image: circleci/ruby:2.5
    environment:
      BUNDLE_PATH: ~/repo/vendor/bundle
    steps:
      - checkout
      - run:
          name: Setup
          command: chown -R $USER:$USER ./bin | ls -l | ./bin/setup
      # - run:
      #     name: Bundle Install
      #     command: bundle check || bundle install
      - run:
          name: Jekyll build
          command: bundle exec jekyll build
      - run:
          name: Remove Site Packages
          command: rm -R ./_site/node_modules
      - run:
          name: HTMLProofer tests
          command: |
            bundle exec htmlproofer ./_site \
              --only-4xx \
              --allow-hash-href \
              --assume-extension \
              --check-opengraph \
              --url-ignore "feed.xml"
      - persist_to_workspace:
          root: ./
          paths:
            - _site
workflows:
  version: 2
  test-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master